@Practical.Web.API_HostAddress = http://localhost:5132

GET {{Practical.Web.API_HostAddress}}/api/Products
Accept: application/json

### Get Products with ID 1
GET {{Practical.Web.API_HostAddress}}/api/Products/1
Accept: application/json
###

### Create a New Product
POST {{Practical.Web.API_HostAddress}}/api/Products
Content-Type: application/json
{
    "Name": "New Product",
    "Price": 39.99,
    "Category": "Books"
}
###

### Update Product with ID 1
PUT {{Practical.Web.API_HostAddress}}/api/Products/1
Content-Type: application/json
{
    "Id": 1,
    "Name": "Updated Product",
    "Price": 49.99,
    "Category": "Electronics"
}
###

### Delete Product with ID 1
DELETE {{Practical.Web.API_HostAddress}}/api/Products/1
###
